[build]
  publish = "public"
  functions = "api"

[[headers]]
  for = "/feed.xml"
  [headers.values]
    Content-Type = "application/rss+xml"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200